apiVersion: v1
kind: Service
metadata:
  name: labs-svc1
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: labs
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: labs-svc2
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: labs
# kubectl apply -f app-service.yaml
